name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
      - name: validate
        run: |
          set -ex
          npm install
          npm run validate
